-- 커스텀 일정 유형 테이블
CREATE TABLE IF NOT EXISTS task_types (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  duration REAL NOT NULL DEFAULT 1,
  color TEXT DEFAULT '#787FFF',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
